# Generated by Django 4.2.8 on 2023-12-30 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_todo_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("age", models.CharField(max_length=100, null=True)),
                ("gender", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="todo", name="task_content", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="creater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task.creater",
            ),
        ),
    ]
