# Generated by Django 4.2.8 on 2023-12-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_creater_alter_todo_complete_alter_todo_created_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Creater", new_name="Employee",),
        migrations.RenameField(
            model_name="todo", old_name="creater", new_name="employee",
        ),
    ]
