# Generated by Django 4.2.8 on 2024-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_owner_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="createuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True)),
                ("password", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
