# Generated by Django 4.2.8 on 2024-01-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_createuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuser",
            name="username",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
