# Generated by Django 4.2.8 on 2024-01-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_blogger_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blogger_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task.blogger",
            ),
        ),
    ]
